DROP TABLE IF EXISTS REGISTER;

CREATE TABLE REGISTER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_name VARCHAR(250) UNIQUE NOT NULL,
  password VARCHAR(250) NOT NULL,
  dob VARCHAR(250) NOT NULL,
  payment_card_number VARCHAR(19) NOT NULL
);